# Usa la imagen oficial de Node.js como base
FROM node:18-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Instala pnpm globalmente
RUN npm install -g pnpm

# Copia los archivos de la aplicación Vue al contenedor
COPY package*.json pnpm-lock.yaml ./

# Instala las dependencias usando pnpm
RUN pnpm install

# Instala las definiciones de tipo de Node.js
RUN pnpm add -D @types/node

# Copia el resto del código fuente al contenedor
COPY . .

# Expone el puerto en el que se ejecutará la aplicación
EXPOSE 8080

# Comando para construir la aplicación Vue
CMD ["pnpm", "run", "serve"]
